repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
        - id: mypy
          additional_dependencies: [pydantic]  # add if use pydantic
-   repo: local
    hooks:
      - id: pytest-cov
        name: pytest-cov
        stages: [commit]
        language: system
        entry: pytest --cov=country_codify_numbers/ tests/ --cov-fail-under=70
        pass_filenames: false
        always_run: true
